site_name: cc-uv-test
repo_url: https://github.com/lukemcguire/cc-uv-test
site_url: https://lukemcguire.github.io/cc-uv-test
site_description: Just messing around with cookiecutter.
site_author: Luke McGuire
edit_uri: edit/main/docs/
repo_name: lukemcguire/cc-uv-test
copyright: Maintained by <a href="https://lukemcguire.com">lukemcguire</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [cc_uv_test]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lukemcguire/cc-uv-test
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cc-uv-test

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
